# Generated by Django 5.2.5 on 2025-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0002_gastofijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
    ]
