# Generated by Django 5.2.5 on 2025-08-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0003_gasto_imagen_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='gastofijo',
            name='categoria',
        ),
    ]
