# Generated by Django 5.2.5 on 2025-08-21 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0004_remove_categoria_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del vencimiento (ej: Pago de tarjeta, Renovación de seguro)', max_length=200)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha en que vence')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, se mostrarán las advertencias')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vencimiento',
                'verbose_name_plural': 'Vencimientos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
