# Generated by Django 5.2.5 on 2025-08-21 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0005_vencimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del logro', max_length=100)),
                ('descripcion', models.TextField(help_text='Descripción detallada del logro')),
                ('tipo', models.CharField(choices=[('ahorro', 'Ahorro'), ('racha', 'Racha'), ('meta', 'Meta'), ('especial', 'Especial')], help_text='Tipo de logro', max_length=20)),
                ('icono', models.CharField(default='fas fa-trophy', help_text='Clase CSS del icono', max_length=50)),
                ('color', models.CharField(default='warning', help_text='Color del badge (Bootstrap)', max_length=20)),
                ('puntos', models.IntegerField(default=10, help_text='Puntos que otorga este logro')),
                ('condicion_valor', models.DecimalField(blank=True, decimal_places=2, help_text='Valor necesario para obtener el logro', max_digits=10, null=True)),
                ('condicion_dias', models.IntegerField(blank=True, help_text='Días necesarios para obtener el logro', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['tipo', 'puntos'],
            },
        ),
        migrations.CreateModel(
            name='Racha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio de la racha')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin de la racha (null si está activa)', null=True)),
                ('dias_consecutivos', models.IntegerField(default=1, help_text='Días consecutivos sin gastos innecesarios')),
                ('activa', models.BooleanField(default=True, help_text='Si la racha está actualmente activa')),
                ('monto_limite_diario', models.DecimalField(decimal_places=2, default=50, help_text='Límite diario para considerar gastos innecesarios', max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha',
                'verbose_name_plural': 'Rachas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('valor_alcanzado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor que alcanzó el usuario', max_digits=10, null=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastitos.logro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro de Usuario',
                'verbose_name_plural': 'Logros de Usuarios',
                'ordering': ['-fecha_obtenido'],
                'unique_together': {('usuario', 'logro')},
            },
        ),
    ]
