# Generated by Django 5.2.5 on 2025-08-21 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0006_logro_racha_logrousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAhorro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la meta (ej: Viaje a Europa, Auto nuevo)', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la meta')),
                ('monto_objetivo', models.DecimalField(decimal_places=2, help_text='Monto total a ahorrar', max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('monto_ahorrado', models.DecimalField(decimal_places=2, default=0, help_text='Monto ya ahorrado', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_objetivo', models.DateField(help_text='Fecha límite para alcanzar la meta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('icono', models.CharField(default='fas fa-piggy-bank', help_text='Clase CSS del icono', max_length=50)),
                ('color', models.CharField(default='primary', help_text='Color del tema (Bootstrap)', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta de Ahorro',
                'verbose_name_plural': 'Metas de Ahorro',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
