# Generated by Django 5.2.5 on 2025-08-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0007_metaahorro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metaahorro',
            name='color',
            field=models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('info', 'Celeste'), ('warning', 'Amarillo'), ('danger', 'Rojo'), ('secondary', 'Gris'), ('dark', 'Negro'), ('purple', 'Morado'), ('pink', 'Rosa'), ('orange', 'Naranja')], default='primary', help_text='Color del tema (Bootstrap)', max_length=20),
        ),
        migrations.AlterField(
            model_name='metaahorro',
            name='icono',
            field=models.CharField(choices=[('piggy-bank', '🐷 Alcancía'), ('car', '🚗 Auto'), ('plane', '✈️ Viaje'), ('home', '🏠 Casa'), ('graduation-cap', '🎓 Educación'), ('ring', '💍 Boda'), ('baby', '👶 Bebé'), ('laptop', '💻 Tecnología'), ('bicycle', '🚲 Bicicleta'), ('camera', '📷 Cámara'), ('gamepad', '🎮 Videojuegos'), ('music', '🎵 Música'), ('gift', '🎁 Regalo'), ('heart', '❤️ Salud'), ('star', '⭐ Sueño')], default='piggy-bank', help_text='Ícono de la meta', max_length=50),
        ),
    ]
