# Generated by Django 5.2.5 on 2025-08-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastitos', '0008_alter_metaahorro_color_alter_metaahorro_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaahorro',
            name='moneda',
            field=models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', help_text='Moneda del objetivo', max_length=3),
        ),
    ]
